server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/politemic?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mail:
    host: smtp.163.com
    port: 465
    username: 15122301381@163.com
    password: #自己的配置
    protocol: smtps
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #必须配置这个，生产者才会确认回调
    publisher-confirm-type: correlated
    publisher-returns: true
    #重要，手动开启消费者ACK，控制消息在MQ中的删除、重发
    listener:
      simple:
        acknowledge-mode: MANUAL
  #  序列化时间的格式和时区
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 7
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000

# logback日志配置文件
logging:
  config: classpath:logback.cfg.dev.xml

mybatis:
  type-aliases-package: com.xbh.politemic.biz.*.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:com/xbh/politemic/biz/*/mapper/*.xml