spring:
  application:
    name: politemic
  profiles:
    active: dev
server:
  servlet:
    context-path: /${spring.application.name}
knife4j:
  # 开启增强配置
  enable: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: 123456